'use strict';
const definitions=[{actor:'acolyte',clip:'heal',name:'Acolyte · leczenie',cue:'heal',duration:120},{actor:'acolyte',clip:'buff',name:'Acolyte · wzmocnienie',cue:'buff',duration:120},{actor:'bulwark',clip:'attack',name:'Bulwark · shield bash',cue:'bash',duration:320}];
let audio;
async function sound(kind){if(!document.querySelector('#sound').checked)return;audio??=new AudioContext();await audio.resume();for(const t of DungeonHD2NpcCues.cues[kind]){const at=audio.currentTime+.002+t.delay;const o=audio.createOscillator(),g=audio.createGain();o.type=t.type;o.frequency.setValueAtTime(t.frequency,at);o.frequency.linearRampToValueAtTime(t.endFrequency,at+t.duration);g.gain.setValueAtTime(.0001,at);g.gain.linearRampToValueAtTime(t.gain,at+.01);g.gain.exponentialRampToValueAtTime(.0001,at+t.duration);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+t.duration+.02);}}
const labels={charge:'Przygotowanie',melee:'Cios',bolt:'Pocisk',heal:'Leczenie',buff:'Wzmocnienie',hex:'Klątwa',venom:'Jad',bash:'Tarcza',rift:'Szczelina',chain:'Łańcuch',blink:'Teleport',slam:'Uderzenie',aura:'Aura'};
for(const cue of Object.keys(DungeonHD2NpcCues.cues)){const b=document.createElement('button');b.textContent=labels[cue];b.onclick=()=>sound(cue);document.querySelector('#sounds').append(b);}
const cards=definitions.map(d=>{const el=document.createElement('section');el.className='card';el.innerHTML=`<h2>${d.name}</h2><canvas width="360" height="320"></canvas><small>Wczytywanie…</small><button data-action="prepare">Przygotuj</button><button data-action="release">Wykonaj</button><button data-action="cancel">Anuluj</button>`;document.querySelector('#cards').append(el);const card={...d,el,frames:[],mode:'idle',start:0};for(const b of el.querySelectorAll('button'))b.onclick=()=>{card.mode=b.dataset.action;card.start=performance.now();if(card.mode==='prepare')sound('charge');if(card.mode==='release')sound(card.cue);};return card;});
let revision=0;
async function load(){const rev=++revision;const direction=document.querySelector('#direction').value;await Promise.all(cards.map(async card=>{const frames=await Promise.all(Array.from({length:8},async(_,i)=>{const im=new Image();im.src=`../../assets/hd/all-v2/${card.actor}/${direction}-${card.clip}-${String(i+1).padStart(2,'0')}.png`;await im.decode();return im;}));if(rev!==revision)return;card.frames=frames;card.mode='idle';}));if(rev===revision)document.body.dataset.loaded=direction;}
function tick(now){for(const c of cards){if(!c.frames.length)continue;let frame=0;const elapsed=now-c.start;if(c.mode==='prepare')frame=Math.min(4,Math.floor(elapsed/64));if(c.mode==='release'){frame=Math.min(7,5+Math.floor(elapsed/(c.duration/3)));if(elapsed>c.duration)c.mode='idle';}const ctx=c.el.querySelector('canvas').getContext('2d');ctx.clearRect(0,0,360,320);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(180,263,48,8,0,0,Math.PI*2);ctx.fill();ctx.drawImage(c.frames[frame],52,12,256,256);c.el.querySelector('small').textContent=`${c.mode==='prepare'?'Przygotowanie':c.mode==='release'?'Wykonanie':'Spoczynek'} · klatka ${frame+1}/8`;c.el.dataset.frame=String(frame+1);c.el.dataset.mode=c.mode;}requestAnimationFrame(tick);}
document.querySelector('#direction').onchange=load;load().catch(e=>{document.body.dataset.error=e.message;});requestAnimationFrame(tick);
