import { RULESET_RELEASE_STATES } from "./registry.js";
import {
  V08_CAMP_TRANSACTION_POLICY,
  V08_META_1_DESCRIPTOR,
  createV08Meta1Ruleset
} from "./v08-meta-1/index.js";
import { normalizeFatalPresentationCauseV08 } from "./v08-meta-1/life-policy.js";

const LEGACY_FATAL_CAPABILITIES = Object.freeze({
  fatalPresentationCauseMode: "strip"
});
const CURRENT_FATAL_CAPABILITIES = Object.freeze({
  fatalPresentationCauseMode: "retain"
});
const LOCAL_BOUNDARY_CAPABILITIES = Object.freeze({
  fatalPresentationCauseMode: "retain",
  boundarySettlementMode: "event-journal-v1"
});
const POST_ROOM_PACT_CAPABILITIES = Object.freeze({
  fatalPresentationCauseMode: "retain",
  boundarySettlementMode: "event-journal-v1",
  postRoomPactSettlement: "post-room-pact-v1"
});
const BOUNDED_PROC_CAPABILITIES = Object.freeze({
  ...POST_ROOM_PACT_CAPABILITIES,
  boundedProcClaims: "v1"
});
const CANONICAL_CHEST_CAPABILITIES = Object.freeze({
  ...BOUNDED_PROC_CAPABILITIES,
  canonicalChestOutcomes: "v1"
});
const EARLY_BALANCE_OTTER_CAPABILITIES = Object.freeze({
  ...CANONICAL_CHEST_CAPABILITIES,
  earlyBalanceOtterRepair: "v1"
});
const BOUNDED_COMBAT_RESOURCES_CAPABILITIES = Object.freeze({
  ...EARLY_BALANCE_OTTER_CAPABILITIES,
  canonicalPotionResources: "v1",
  boundedCombatResources: "v1"
});
const RANKED_START_RESOURCE_PARITY_CAPABILITIES = Object.freeze({
  ...BOUNDED_COMBAT_RESOURCES_CAPABILITIES,
  rankedStartResourceParity: "v1"
});
const LOCAL_ENVIRONMENTS = Object.freeze(["test", "local"]);
const PRODUCTION_ENVIRONMENTS = Object.freeze(["test", "local", "production"]);
const V08_ELIXIR_IDS = new Set(
  V08_CAMP_TRANSACTION_POLICY.elixirs.map((entry) => entry.id)
);

function compatibleFatalRequest(request, capabilities) {
  if (
    !request ||
    typeof request !== "object" ||
    !Object.hasOwn(request, "presentationCause")
  ) return request;
  const presentationCause = normalizeFatalPresentationCauseV08(request);
  if (capabilities.fatalPresentationCauseMode === "retain") {
    return { ...request, presentationCause };
  }
  const legacyRequest = { ...request };
  delete legacyRequest.presentationCause;
  return legacyRequest;
}

function createCapabilityBoundRuleset(rulesetHash, capabilities) {
  const ruleset = createV08Meta1Ruleset({ rulesetHash, capabilities });
  return Object.freeze({
    ...ruleset,
    capabilities,
    isKnownElixirId(elixirId) {
      return V08_ELIXIR_IDS.has(elixirId);
    },
    async reportFatalEvent(state, request, context = {}) {
      return ruleset.reportFatalEvent(
        state,
        compatibleFatalRequest(request, capabilities),
        context
      );
    }
  });
}

function createReleaseDescriptor(rulesetHash, status, allowedEnvironments, capabilities) {
  return Object.freeze({
    ...V08_META_1_DESCRIPTOR,
    rulesetHash,
    status,
    allowedEnvironments,
    capabilities,
    createRuleset: () => createCapabilityBoundRuleset(rulesetHash, capabilities)
  });
}

export const V08_META_1_LOCAL_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_DESCRIPTOR.rulesetHash,
  RULESET_RELEASE_STATES.LOCAL_RELEASE_CANDIDATE,
  LOCAL_ENVIRONMENTS,
  RANKED_START_RESOURCE_PARITY_CAPABILITIES
);

export const V08_META_1_PACT_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:5c3df81af373b68fce4d8fa242fb61c29b7c3d4ca78d6865d2ee51a58bbab3dd";

export const V08_META_1_START_RESOURCE_PARITY_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:9d6069993fd07784ecfdc146825a8a7b82cde1fd7412f351aeba1ab86c539dbe";

export const V08_META_1_PRODUCTION_RULESET_HASH =
  V08_META_1_DESCRIPTOR.rulesetHash;

export const V08_META_1_CHEST_HP_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:48b5bd86604a5f8dae58a4dcf2b1ed9a72252b3e4942fc20693b3e0a8e91438e";

export const V08_META_1_POTION_MERCHANT_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:bf17a65dc721066bf11a1c34063cc18254fe97766852827719eb6aabf36042fa";

export const V08_META_1_OTTER_REPAIR_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:91065f3c515fbc2f996ba74a9fbbcab3d2ce013077af306afd51929e64e1af59";

export const V08_META_1_GOLD_CONTEXT_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:5bf4a0fbf2583b9b59ae050eebdd324bc09038b3aed6d2090cb3a4e5481f79eb";

export const V08_META_1_CANONICAL_CHEST_CONTEXT_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:51a86cf41299257475530a356b98381ac828fdb0ec22e77eff0ded99f1758617";

export const V08_META_1_CANONICAL_CHEST_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:0a922d5567e7cfba56644e915ac0e331ac74aa3fcc3a2aed478440d64e9878f7";

export const V08_META_1_CHEST_CARRY_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:35707f6b5ea8b1ad18251dce5e6c18b87653893aad705b6c5543fdd140b88067";

export const V08_META_1_BOUNDED_PROC_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:76514cf9e5c89079571a5be117ce84f949d7a3f5ed441d973adc05c95c6dde3c";

export const V08_META_1_GOLD_SYNC_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:87c30b2c011b5103398f9b03f6bf018d71f2a35427c0a04ef7a31b2559a7a6d9";

export const V08_META_1_INTEGRITY_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:0672eb9aaae11865ebae75a4c6d6dc77cc29f4a079afe562355172d26f073bca";

export const V08_META_1_PLAYTEST_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:bc0d548d204557d0cc0ec7f8a358e18246778a13b27c58f5c6cdd73e73621711";

export const V08_META_1_BOUNDARY_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:d784208aad891119b71c52324cea358997ee376313914d5799affa68c8678ff3";

export const V08_META_1_HD_BOOT_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:7027a84ff06d6d9304e3d8e4343dbd6b3071c8bec734fad10b85981fa92347e8";

export const V08_META_1_SCORE_CARRY_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:e4175a6cb29f576a3ad85357a433d6595eb7e9d19a6c5f47ed125ecfe9ae538e";

export const V08_META_1_R2_PRODUCTION_RULESET_HASH =
  "sha256:956251f158e55a0a47f9e43d5680d9aae66a22045c833bd76b8798cdc00e012e";

export const V08_META_1_WARDEN_HOTFIX_RULESET_HASH =
  "sha256:31124ece34ef1c82a28bb977467d169eade8b34c0c13360d7054ab1684e5fe36";

export const V08_META_1_PREVIOUS_PRODUCTION_RULESET_HASH =
  "sha256:08dfa4f97d91b4f21dbfae7232246125ddbbc6a0270cf81a9e1ed012e5f5d403";

export const V08_META_1_LEGACY_PRODUCTION_RULESET_HASH =
  "sha256:0bf00607056dbf3c30ffe57bbcfc77cea95b21c9ccc23aa985ec555856d1cbd6";

export const V08_META_1_LEGACY_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_LEGACY_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_R2_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_R2_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_WARDEN_HOTFIX_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_WARDEN_HOTFIX_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_SCORE_CARRY_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_SCORE_CARRY_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_HD_BOOT_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_HD_BOOT_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_BOUNDARY_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_BOUNDARY_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_PLAYTEST_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_PLAYTEST_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LEGACY_FATAL_CAPABILITIES
);

export const V08_META_1_INTEGRITY_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_INTEGRITY_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  CURRENT_FATAL_CAPABILITIES
);

export const V08_META_1_GOLD_SYNC_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_GOLD_SYNC_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LOCAL_BOUNDARY_CAPABILITIES
);

export const V08_META_1_PACT_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_PACT_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  LOCAL_BOUNDARY_CAPABILITIES
);

export const V08_META_1_BOUNDED_PROC_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_BOUNDED_PROC_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  POST_ROOM_PACT_CAPABILITIES
);

export const V08_META_1_CHEST_CARRY_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_CHEST_CARRY_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  BOUNDED_PROC_CAPABILITIES
);

export const V08_META_1_CANONICAL_CHEST_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_CANONICAL_CHEST_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  CANONICAL_CHEST_CAPABILITIES
);

export const V08_META_1_CANONICAL_CHEST_CONTEXT_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_CANONICAL_CHEST_CONTEXT_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  CANONICAL_CHEST_CAPABILITIES
);

export const V08_META_1_GOLD_CONTEXT_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_GOLD_CONTEXT_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  CANONICAL_CHEST_CAPABILITIES
);

export const V08_META_1_OTTER_REPAIR_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_OTTER_REPAIR_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  CANONICAL_CHEST_CAPABILITIES
);

export const V08_META_1_POTION_MERCHANT_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_POTION_MERCHANT_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  EARLY_BALANCE_OTTER_CAPABILITIES
);

export const V08_META_1_CHEST_HP_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_CHEST_HP_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  BOUNDED_COMBAT_RESOURCES_CAPABILITIES
);

export const V08_META_1_START_RESOURCE_PARITY_PREVIOUS_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_START_RESOURCE_PARITY_PREVIOUS_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  BOUNDED_COMBAT_RESOURCES_CAPABILITIES
);

export const V08_META_1_PRODUCTION_RELEASE_DESCRIPTOR = createReleaseDescriptor(
  V08_META_1_PRODUCTION_RULESET_HASH,
  RULESET_RELEASE_STATES.PRODUCTION_RELEASED,
  PRODUCTION_ENVIRONMENTS,
  RANKED_START_RESOURCE_PARITY_CAPABILITIES
);
